-- Canonical fresh-database definition, for Oracle. Run once in an empty schema.
-- Descriptions may contain Markdown. Demo rows are loaded separately.
--
-- Every statement is followed by a line holding only "/", the convention
-- SQL*Plus uses and the one scripts/init.js splits the file on. Oracle has no
-- equivalent of PostgreSQL's simple protocol, where a whole file of statements
-- can be handed over as one string, so the file has to be cut up first.
--
-- Four spellings recur below, and they are Oracle's doing rather than this
-- schema's:
--
--   * TEXT is CLOB. VARCHAR2 stops at 4000 bytes, and the descriptions,
--     reviews and image lists this schema stores are unbounded.
--   * boolean is NUMBER(1) with a CHECK, which is what Oracle has instead.
--     src/db/execute.js turns those back into true and false on the way out,
--     so the API still speaks in booleans.
--   * CURRENT_TIMESTAMP is LOCALTIMESTAMP. The first is a TIMESTAMP WITH TIME
--     ZONE and would be converted on the way into every TIMESTAMP column; the
--     second is already the type these columns hold.
--   * PostgreSQL's ON DELETE RESTRICT is written as nothing at all. NO ACTION
--     is Oracle's only behaviour for a foreign key, and the deletes this schema
--     actually cares about are refused by triggers outright.
--
-- Identity columns are GENERATED BY DEFAULT ON NULL rather than GENERATED
-- ALWAYS. The demo rows in sql/test_insert name their own courier and country
-- ids — the courier rows are keyed by user id, so they have to — and a schema
-- that refused them would make the seed file unwritable.

--tables
CREATE TABLE countries(
    country_id VARCHAR2(10 CHAR) PRIMARY KEY,
    country_name VARCHAR2(200 CHAR) NOT NULL UNIQUE
)
/
CREATE TABLE locations(
    location_id NUMBER(10) GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    -- VARCHAR2, not CLOB, where every other CLOB in this schema is unbounded
    -- prose: an address is a key, not a document. The API caps it at 500
    -- characters, the seed files join on it, and Oracle will not compare a LOB
    -- with `=` or with LIKE — a CLOB here would make the fixture unwritable and
    -- the column unsearchable for no gain.
    street_address VARCHAR2(500 CHAR) NOT NULL,
    postal_code VARCHAR2(30 CHAR),
    city VARCHAR2(120 CHAR) NOT NULL,
    state_province VARCHAR2(120 CHAR),
    country_id VARCHAR2(10 CHAR) REFERENCES countries(country_id) ON DELETE CASCADE NOT NULL
)
/
CREATE TABLE roles(
    role_id NUMBER(10) GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    role_name VARCHAR2(40 CHAR) NOT NULL UNIQUE,
    description CLOB DEFAULT NULL
)
/
-- Authorization uses roles resolved by the API; no unused permission tables.
CREATE TABLE users
(
    user_id NUMBER(10) GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    user_role NUMBER(10) REFERENCES roles(role_id) ON DELETE SET NULL,--call a trigger to disable user
    name VARCHAR2(300 CHAR) NOT NULL,
    password_hash CLOB NOT NULL,
    phone_numbers VARCHAR2(20 CHAR),
    pfp CLOB,
    email VARCHAR2(60 CHAR) UNIQUE NOT NULL,
    address NUMBER(10) REFERENCES locations(location_id) ON DELETE SET NULL,
    created_at TIMESTAMP DEFAULT LOCALTIMESTAMP,
    point NUMBER(10) DEFAULT 0 NOT NULL,
    token_version NUMBER(10) DEFAULT 0 NOT NULL,
    active_status VARCHAR2(20 CHAR) DEFAULT 'active' NOT NULL CHECK(active_status IN ('active','disabled'))--call a trigger to disable shops, delivery_personnel
)
/
--raise exception when deleting from shops
CREATE TABLE shops(
    shop_id NUMBER(10) GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    owner NUMBER(10) REFERENCES users(user_id) NOT NULL ,
    name VARCHAR2(300 CHAR) NOT NULL,
    logo CLOB,
    cover_photo CLOB,
    description CLOB,
    -- The shop's running balance: sales credit it, wholesale buying debits it,
    -- recharges and admin refunds credit it, approved customer returns debit it.
    -- Deliberately NOT CHECK (balance >= 0). A vendor must not be able to refuse
    -- a customer's return because the shop has already spent the money, so the
    -- column is allowed to go negative; the purchase path is what refuses to
    -- spend money that is not there, with `balance >= cost` in its predicate.
    balance NUMBER(12,2) DEFAULT 0 NOT NULL,
    created_at TIMESTAMP DEFAULT LOCALTIMESTAMP,
    active_status VARCHAR2(20 CHAR) DEFAULT 'active' NOT NULL CHECK(active_status IN ('active','disabled','pending')),--'pending' until an administrator approves the shop; when disabled,call a trigger to set product(discontinued) to true   --kept 'active' by default so seeded data and direct inserts stay live; the vendor path writes 'pending' explicitly
    phone_numbers VARCHAR2(20 CHAR),
    address NUMBER(10) REFERENCES locations(location_id) ON DELETE SET NULL
)
/
CREATE TABLE categories(
    category_id NUMBER(10) GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    name VARCHAR2(300 CHAR) NOT NULL,
    description CLOB,
    parent_category NUMBER(10) DEFAULT NULL REFERENCES categories(category_id) ON DELETE CASCADE
)
/
--raise exception when deleting from master_products
CREATE TABLE master_products(
    master_prod_id NUMBER(10) GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    manufacturer VARCHAR2(300 CHAR) NOT NULL,
    images CLOB,--will use table for images later
    description CLOB,
    category_id NUMBER(10) REFERENCES categories(category_id) NOT NULL ,
    wholesale_price NUMBER(12,2) NOT NULL CHECK (wholesale_price >= 0),
    name VARCHAR2(300 CHAR) NOT NULL,
    active_status VARCHAR2(20 CHAR) DEFAULT 'available' NOT NULL CHECK(active_status IN ('available','discontinued')),
    date_created TIMESTAMP DEFAULT LOCALTIMESTAMP
)
/
--raise exception when deleting from products

CREATE TABLE products(
    prod_id NUMBER(10) GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    name VARCHAR2(300 CHAR) NOT NULL,
    images CLOB,--will use table for images later
    master_prod_id NUMBER(10) REFERENCES master_products(master_prod_id) NOT NULL ,
    description CLOB,
    shop_id NUMBER(10) REFERENCES shops(shop_id) NOT NULL,
    in_stock NUMBER(10) DEFAULT 0 NOT NULL CHECK (in_stock >= 0),
    discontinued NUMBER(1) DEFAULT 0 NOT NULL CHECK (discontinued IN (0,1)),
    created_at TIMESTAMP DEFAULT LOCALTIMESTAMP,
    unit_price NUMBER(12,2) NOT NULL CHECK (unit_price >= 0)
)
/
-- Records a vendor's wholesale acquisition before the item is offered for sale.
CREATE TABLE shop_purchases(
    purchase_id NUMBER(10) GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    shop_id NUMBER(10) REFERENCES shops(shop_id) NOT NULL,
    master_prod_id NUMBER(10) REFERENCES master_products(master_prod_id) NOT NULL,
    quantity NUMBER(10) NOT NULL CHECK (quantity > 0),
    wholesale_unit_price NUMBER(12,2) NOT NULL CHECK (wholesale_unit_price >= 0),
    purchased_at TIMESTAMP DEFAULT LOCALTIMESTAMP NOT NULL
)
/
-- The compensation half of removing a listing. A hard DELETE from products is
-- impossible (see fn_prevent_delete below), so an administrator "removing" a
-- listing means discontinued = 1 plus paying the vendor back for the stock
-- they still hold. This is the ledger of those payments; shops.balance is the
-- running total.
CREATE TABLE vendor_refunds(
    refund_id NUMBER(10) GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    shop_id NUMBER(10) REFERENCES shops(shop_id) NOT NULL,
    prod_id NUMBER(10) REFERENCES products(prod_id) NOT NULL,
    master_prod_id NUMBER(10) REFERENCES master_products(master_prod_id) NOT NULL,
    units NUMBER(10) NOT NULL CHECK (units >= 0),
    -- amount / units, and therefore NULL when units is 0: the price of no units
    -- is not a number. This averages the attributed wholesale purchase prices.
    unit_amount NUMBER(12,2),
    amount NUMBER(12,2) NOT NULL CHECK (amount >= 0),
    reason VARCHAR2(40 CHAR) NOT NULL CHECK (reason IN ('admin_removal', 'shop_closed')),
    removed_by NUMBER(10) REFERENCES users(user_id) NOT NULL,
    created_at TIMESTAMP DEFAULT LOCALTIMESTAMP NOT NULL
)
/
-- A shop funding its own balance. There is no payment gateway, so this is a
-- record of a recharge rather than a card charge — the API says as much in its
-- own response. The ledger half of the balance; shops.balance is the running total.
CREATE TABLE shop_topups(
    topup_id NUMBER(10) GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    shop_id NUMBER(10) REFERENCES shops(shop_id) NOT NULL,
    amount NUMBER(12,2) NOT NULL CHECK (amount > 0),
    method VARCHAR2(40 CHAR) NOT NULL CHECK (method IN ('card', 'bank_transfer', 'cash')),
    created_at TIMESTAMP DEFAULT LOCALTIMESTAMP NOT NULL
)
/
CREATE TABLE attributes(
    attribute_id NUMBER(10) GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    name VARCHAR2(300 CHAR) NOT NULL,
    description CLOB
)
/
CREATE TABLE category_attributes(
    category_id NUMBER(10) REFERENCES categories(category_id) ON DELETE CASCADE NOT NULL ,
    attribute_id NUMBER(10) REFERENCES attributes(attribute_id) ON DELETE CASCADE NOT NULL ,
    PRIMARY KEY(category_id,attribute_id)
)
/
CREATE TABLE attribute_values(
    master_prod_id NUMBER(10) REFERENCES master_products(master_prod_id) ON DELETE CASCADE NOT NULL,
    attribute_id NUMBER(10) REFERENCES attributes(attribute_id) ON DELETE CASCADE NOT NULL ,
    attrib_value VARCHAR2(300 CHAR) NOT NULL,
    PRIMARY KEY(master_prod_id,attribute_id)
)
/
CREATE TABLE cart_items(
    user_id NUMBER(10) REFERENCES users(user_id) ON DELETE CASCADE NOT NULL ,
    prod_id NUMBER(10) REFERENCES products(prod_id) ON DELETE CASCADE NOT NULL ,
    quantity NUMBER(10) NOT NULL CHECK (quantity > 0),
    PRIMARY KEY(user_id,prod_id)
)
/
CREATE TABLE wish_list_items(
    user_id NUMBER(10) REFERENCES users(user_id) ON DELETE CASCADE NOT NULL ,
    prod_id NUMBER(10) REFERENCES products(prod_id) ON DELETE CASCADE NOT NULL ,
    PRIMARY KEY(user_id,prod_id)
)
/
CREATE TABLE product_reviews(
    user_id NUMBER(10) REFERENCES users(user_id) ON DELETE CASCADE NOT NULL ,
    prod_id NUMBER(10) REFERENCES products(prod_id) ON DELETE CASCADE NOT NULL ,
    rating NUMBER(10) CHECK(rating BETWEEN 1 AND 5) NOT NULL,
    review CLOB,
    last_modified TIMESTAMP DEFAULT LOCALTIMESTAMP,
    PRIMARY KEY(user_id,prod_id)
)
/
CREATE TABLE shop_reviews(
    user_id NUMBER(10) REFERENCES users(user_id) ON DELETE CASCADE NOT NULL,
    shop_id NUMBER(10) REFERENCES shops(shop_id) ON DELETE CASCADE NOT NULL,
    rating NUMBER(10) CHECK(rating BETWEEN 1 AND 5) NOT NULL,
    review CLOB,
    last_modified TIMESTAMP DEFAULT LOCALTIMESTAMP,
    PRIMARY KEY(user_id,shop_id)
)
/
--raise exception when deleting from delivery_personnel
CREATE TABLE delivery_personnel(
    delivery_person_id NUMBER(10) REFERENCES users(user_id) PRIMARY KEY,
    vehicle_info CLOB,--free-text notes; the fields below are the parts worth filtering on
    vehicle_type VARCHAR2(40 CHAR),--motorcycle/car/van/bicycle
    vehicle_number VARCHAR2(40 CHAR),--registration or plate
    license_number VARCHAR2(60 CHAR),
    vehicle_model VARCHAR2(120 CHAR),
    active_status VARCHAR2(20 CHAR) DEFAULT 'available' NOT NULL CHECK(active_status IN ('available','on_delivery','unavailable')),--when :new.active_status='unavailable' when order still 'shipped' or 'pending', set orders.delivery personnel:=null and order_status:='pending'
    earnings NUMBER(12,2)

)
/
--restrict deletion
CREATE TABLE orders(
    order_id NUMBER(10) GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    order_status VARCHAR2(20 CHAR) DEFAULT 'pending' NOT NULL CHECK(order_status IN ('pending','shipped','delivered','cancelled')),-- cancellation preserves history and restores stock
    user_id NUMBER(10) REFERENCES users(user_id) NOT NULL,
    delivery_person_id NUMBER(10) DEFAULT NULL REFERENCES delivery_personnel(delivery_person_id),
    delivered_at TIMESTAMP DEFAULT NULL,
    total_amount NUMBER(12,2) DEFAULT 0 NOT NULL CHECK (total_amount >= 0),
    -- What the customer pays for the trip, and therefore what the courier is
    -- paid for it. Written once at checkout (RECORD_DELIVERY_COST) and read back
    -- by settle_delivery, so changing the pay constants cannot retroactively
    -- move money on an order that was already placed.
    delivery_cost NUMBER(12,2) DEFAULT 0 NOT NULL,
    created_at TIMESTAMP DEFAULT LOCALTIMESTAMP,
    shipping_address NUMBER(10) REFERENCES locations(location_id) NOT NULL
)
/
CREATE TABLE payments(
    transaction_id NUMBER(10) GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    order_id NUMBER(10) REFERENCES orders(order_id) NOT NULL,
    -- NUMBER(12,2) where PostgreSQL said DECIMAL. Unconstrained, the column
    -- would store the sum it is given at that sum's own scale and hand back a
    -- number with no decimals; the API has always shown two.
    amount NUMBER(12,2) NOT NULL,
    payment_method VARCHAR2(40 CHAR) CHECK(payment_method IN ('prepaid','cash_on_delivery')) NOT NULL,
    payment_status VARCHAR2(40 CHAR) DEFAULT 'pending' NOT NULL CHECK(payment_status IN ('pending','completed','failed')),
    paid_at TIMESTAMP DEFAULT LOCALTIMESTAMP
)
/
CREATE TABLE order_items(
    order_id NUMBER(10) REFERENCES orders(order_id) NOT NULL,
    prod_id NUMBER(10) REFERENCES products(prod_id) NOT NULL,
    quantity NUMBER(10) NOT NULL CHECK (quantity > 0),
    unit_price NUMBER(12,2) NOT NULL CHECK (unit_price >= 0),
    PRIMARY KEY(order_id,prod_id)
)
/
-- A customer sending goods back, and the vendor's decision on it.
--
-- Declared here, at the end of the tables, because it references orders and
-- delivery_personnel — both of which are themselves declared late, so a
-- definition further up the file could not be parsed.
--
-- Deliberately a table of its own rather than a fifth value in
-- orders.order_status. A return is a fact about one line of an order, not a state
-- of the whole order: an order of three listings can have one returned and two
-- kept. It also keeps the four order states intact, which matters because
-- fn_guard_order_transition, both review-verification triggers and
-- fn_cleanup_cancelled_order all key on them — a 'returned' state would put an
-- order beyond the reach of every one of those.
--
-- Status is a small state machine, and every transition is a compare-and-set in
-- the API rather than a read followed by a check:
--
--   requested ──▶ approved ──▶ collected ──▶ restocked
--       └──────▶ rejected   (and a rejected request may be made again)
--
-- Money and goods move at different moments on purpose. The refund is recorded
-- and the shop's balance debited at approval, because that is when the shop
-- accepts the obligation. products.in_stock rises at restock, because until the
-- parcel is physically back the shop cannot sell the unit again.
CREATE TABLE product_returns(
    return_id NUMBER(10) GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    order_id NUMBER(10) REFERENCES orders(order_id) NOT NULL,
    prod_id NUMBER(10) REFERENCES products(prod_id) NOT NULL,
    user_id NUMBER(10) REFERENCES users(user_id) NOT NULL, -- the customer
    -- Denormalised from products.shop_id, which is immutable once a listing is
    -- created, so this cannot drift. It is what makes "may this vendor decide it"
    -- and the balance debit single-table predicates.
    shop_id NUMBER(10) REFERENCES shops(shop_id) NOT NULL,
    quantity NUMBER(10) NOT NULL CHECK (quantity > 0),
    reason CLOB,
    status VARCHAR2(20 CHAR) DEFAULT 'requested' NOT NULL
        CHECK (status IN ('requested', 'approved', 'rejected', 'collected', 'restocked')),
    -- quantity × the order line's unit_price, frozen at request time. The order
    -- line's price is itself a snapshot, so this cannot move afterwards.
    refund_amount NUMBER(12,2) NOT NULL CHECK (refund_amount >= 0),
    decision_note CLOB,
    decided_at TIMESTAMP,
    -- Any active courier may collect, which is why this records who did rather
    -- than being constrained to the courier who delivered the order: that person
    -- may since have gone unavailable, and a pickup only one person can perform
    -- is a pickup that can stall forever.
    collected_by NUMBER(10) REFERENCES delivery_personnel(delivery_person_id),
    collected_at TIMESTAMP,
    restocked_at TIMESTAMP,
    created_at TIMESTAMP DEFAULT LOCALTIMESTAMP NOT NULL
)
/
-- The customer side of the refund ledger. The mirror of vendor_refunds and the
-- opposite direction of money: that table is platform → shop, this one is
-- shop → customer. They never share a table for the same reason.
CREATE TABLE customer_refunds(
    refund_id NUMBER(10) GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    return_id NUMBER(10) REFERENCES product_returns(return_id) NOT NULL,
    order_id NUMBER(10) REFERENCES orders(order_id) NOT NULL,
    user_id NUMBER(10) REFERENCES users(user_id) NOT NULL, -- who is paid
    shop_id NUMBER(10) REFERENCES shops(shop_id) NOT NULL,
    amount NUMBER(12,2) NOT NULL CHECK (amount >= 0),
    created_at TIMESTAMP DEFAULT LOCALTIMESTAMP NOT NULL
)
/

-- =========================================================
-- Computed monetary value used by the order-total trigger and checkout reads.
--
-- Rounded here rather than left to the caller: a NUMBER returned from PL/SQL
-- carries no declared scale, so the adapter has nothing to format it by, and
-- every money column in this schema is written to two places.
-- =========================================================
CREATE OR REPLACE FUNCTION fn_order_subtotal(p_order_id NUMBER) RETURN NUMBER IS
    v_total NUMBER;
BEGIN
    SELECT COALESCE(SUM(quantity * unit_price), 0) INTO v_total
    FROM order_items WHERE order_id = p_order_id;
    RETURN ROUND(v_total, 2);
END;
/

-- =========================================================
-- 1. Generic "no hard deletes" guard
--    Used by: users, shops, master_products, products,
--             delivery_personnel, orders
--
--    One procedure rather than six bodies: ORA_DICT_OBJ_NAME is the name of the
--    table whose trigger is running, which is what TG_TABLE_NAME was for.
-- =========================================================
CREATE OR REPLACE PROCEDURE fn_prevent_delete IS
BEGIN
    RAISE_APPLICATION_ERROR(-20001, 'Deletion from table "' || ORA_DICT_OBJ_NAME
        || '" is not allowed. Use an active_status/discontinued flag instead.');
END;
/

CREATE OR REPLACE TRIGGER trg_prevent_delete_users
BEFORE DELETE ON users FOR EACH ROW
BEGIN fn_prevent_delete; END;
/

CREATE OR REPLACE TRIGGER trg_prevent_delete_shops
BEFORE DELETE ON shops FOR EACH ROW
BEGIN fn_prevent_delete; END;
/

CREATE OR REPLACE TRIGGER trg_prevent_delete_master_products
BEFORE DELETE ON master_products FOR EACH ROW
BEGIN fn_prevent_delete; END;
/

CREATE OR REPLACE TRIGGER trg_prevent_delete_products
BEFORE DELETE ON products FOR EACH ROW
BEGIN fn_prevent_delete; END;
/

CREATE OR REPLACE TRIGGER trg_prevent_delete_delivery_personnel
BEFORE DELETE ON delivery_personnel FOR EACH ROW
BEGIN fn_prevent_delete; END;
/

CREATE OR REPLACE TRIGGER trg_prevent_delete_orders
BEFORE DELETE ON orders FOR EACH ROW
BEGIN fn_prevent_delete; END;
/

-- =========================================================
-- 2. Keep orders.total_amount in sync with order_items
--    ("--for calculating order.total_amount")
--
--    A compound trigger, where PostgreSQL had an after-row one. The reason is
--    Oracle's mutating-table rule: a row trigger on order_items may not read
--    order_items, and fn_order_subtotal does exactly that. Collecting the
--    affected orders as the rows go by and summing them once the statement is
--    over is both legal here and one statement where PostgreSQL wrote one per
--    row.
-- =========================================================
CREATE OR REPLACE TRIGGER trg_order_items_recalc_total
FOR INSERT OR UPDATE OR DELETE ON order_items
COMPOUND TRIGGER
    TYPE order_ids IS TABLE OF NUMBER INDEX BY PLS_INTEGER;
    touched order_ids;
    n PLS_INTEGER := 0;

    PROCEDURE remember(p_order_id NUMBER) IS
    BEGIN
        IF p_order_id IS NOT NULL THEN
            n := n + 1;
            touched(n) := p_order_id;
        END IF;
    END;

    AFTER EACH ROW IS
    BEGIN
        IF INSERTING OR UPDATING THEN remember(:NEW.order_id); END IF;
        IF DELETING OR UPDATING THEN remember(:OLD.order_id); END IF;
    END AFTER EACH ROW;

    AFTER STATEMENT IS
    BEGIN
        FOR i IN 1 .. n LOOP
            UPDATE orders SET total_amount = fn_order_subtotal(touched(i))
            WHERE order_id = touched(i);
        END LOOP;
    END AFTER STATEMENT;
END;
/

-- =========================================================
-- 3. Disable a user when their role is removed
--    ("user_role ... on delete set null -- call a trigger to disable user")
-- =========================================================
CREATE OR REPLACE TRIGGER trg_disable_user_on_role_removal
BEFORE UPDATE ON users FOR EACH ROW
WHEN (NEW.user_role IS NULL AND OLD.user_role IS NOT NULL)
BEGIN
    :NEW.active_status := 'disabled';
END;
/

-- =========================================================
-- 4. Discontinue all of a shop's products when the shop is disabled
--    ("active_status ... -- when disabled, call a trigger to set product(discontinued) to true")
-- =========================================================
CREATE OR REPLACE TRIGGER trg_discontinue_products_on_shop_disable
AFTER UPDATE ON shops FOR EACH ROW
WHEN (NEW.active_status = 'disabled' AND OLD.active_status <> 'disabled')
BEGIN
    UPDATE products SET discontinued = 1 WHERE shop_id = :NEW.shop_id;
END;
/

-- =========================================================
-- 5. Free up affected orders when a courier goes "unavailable"
--    ("active_status ... -- when :new.active_status='unavailable' when order
--      still 'shipped' or 'pending', set orders.delivery_person_id:=null
--      and order_status:='pending'")
-- =========================================================
CREATE OR REPLACE TRIGGER trg_release_orders_on_personnel_unavailable
AFTER UPDATE ON delivery_personnel FOR EACH ROW
WHEN (NEW.active_status = 'unavailable' AND OLD.active_status <> 'unavailable')
BEGIN
    UPDATE orders
    SET delivery_person_id = NULL,
        order_status = 'pending'
    WHERE delivery_person_id = :NEW.delivery_person_id
      AND order_status IN ('shipped', 'pending');
END;
/

-- =========================================================
-- 6. Clean up an order when it's cancelled
--    Preserve the purchase history and return reserved stock once.
--
--    A BEFORE trigger, where PostgreSQL had an AFTER one, for one reason:
--    clearing the courier is a change to the very row being cancelled, and an
--    after-row trigger may not update its own table. Writing it into :NEW is how
--    a BEFORE row trigger says the same thing.
-- =========================================================
CREATE OR REPLACE TRIGGER trg_cleanup_cancelled_order
BEFORE UPDATE ON orders FOR EACH ROW
WHEN (NEW.order_status = 'cancelled' AND OLD.order_status <> 'cancelled')
BEGIN
    :NEW.delivery_person_id := NULL;

    -- The listing is named by its table rather than by an alias: Oracle's SET
    -- clause takes a bare column name, so there is no `p` to write on the left
    -- and the subqueries correlate through the table name instead.
    UPDATE products
    SET in_stock = in_stock + (
        SELECT SUM(oi.quantity) FROM order_items oi
        WHERE oi.order_id = :NEW.order_id AND oi.prod_id = products.prod_id)
    WHERE EXISTS (
        SELECT 1 FROM order_items oi
        WHERE oi.order_id = :NEW.order_id AND oi.prod_id = products.prod_id);

    UPDATE payments SET payment_status = 'failed', paid_at = NULL
    WHERE order_id = :NEW.order_id AND payment_status = 'pending';
END;
/

-- =========================================================
-- 7. Cascade a user disable down to their shops and
--    delivery-personnel status
--    ("active_status ... -- call a trigger to disable shops, delivery_personnel")
-- =========================================================
CREATE OR REPLACE TRIGGER trg_disable_user_dependents
AFTER UPDATE ON users FOR EACH ROW
WHEN (NEW.active_status = 'disabled' AND OLD.active_status <> 'disabled')
BEGIN
    -- disable any shops this user owns
    UPDATE shops
    SET active_status = 'disabled'
    WHERE owner = :NEW.user_id
      AND active_status <> 'disabled';

    -- if this user is also delivery personnel, take them off duty
    UPDATE delivery_personnel
    SET active_status = 'unavailable'
    WHERE delivery_person_id = :NEW.user_id
      AND active_status <> 'unavailable';
END;
/

-- =========================================================
-- 7b. Undo the shop half of the cascade when a user is restored
--     An administrator un-banning a user expects the user's shops to come back.
--     Listings deliberately stay discontinued (fn_discontinue_products_on_shop_disable
--     is one-way), so a vendor consciously relists rather than having retired
--     listings silently resurrected.
--     delivery_personnel is deliberately left alone: the disable direction sets a
--     courier 'unavailable', which also releases their in-flight orders, and
--     returning them to 'available' would put them back on duty without opting in.
--     Couriers set their own availability from the delivery workspace.
-- =========================================================
CREATE OR REPLACE TRIGGER trg_enable_user_dependents
AFTER UPDATE ON users FOR EACH ROW
WHEN (NEW.active_status = 'active' AND OLD.active_status <> 'active')
BEGIN
    UPDATE shops
    SET active_status = 'active'
    WHERE owner = :NEW.user_id
      AND active_status = 'disabled';
END;
/

-- A completed delivery is the proof of purchase for a product review.
CREATE OR REPLACE TRIGGER trg_verify_product_review_purchase
BEFORE INSERT OR UPDATE ON product_reviews FOR EACH ROW
DECLARE
    v_proven NUMBER;
BEGIN
    SELECT COUNT(*) INTO v_proven
    FROM orders o
    JOIN order_items oi ON oi.order_id = o.order_id
    JOIN users u ON u.user_id = o.user_id
    JOIN roles r ON r.role_id = u.user_role
    WHERE o.user_id = :NEW.user_id AND oi.prod_id = :NEW.prod_id
      AND o.order_status = 'delivered' AND r.role_name = 'customer';

    IF v_proven = 0 THEN
        RAISE_APPLICATION_ERROR(-20002,
            'Only customers with a delivered purchase of this listing can review it.');
    END IF;

    :NEW.last_modified := LOCALTIMESTAMP;
END;
/

-- The same rule for shop reviews: a delivered order containing one of the
-- shop's listings is the proof of purchase.
CREATE OR REPLACE TRIGGER trg_verify_shop_review_purchase
BEFORE INSERT OR UPDATE ON shop_reviews FOR EACH ROW
DECLARE
    v_proven NUMBER;
BEGIN
    SELECT COUNT(*) INTO v_proven
    FROM orders o
    JOIN order_items oi ON oi.order_id = o.order_id
    JOIN products p ON p.prod_id = oi.prod_id
    JOIN users u ON u.user_id = o.user_id
    JOIN roles r ON r.role_id = u.user_role
    WHERE o.user_id = :NEW.user_id
      AND p.shop_id = :NEW.shop_id
      AND o.order_status = 'delivered'
      AND r.role_name = 'customer';

    IF v_proven = 0 THEN
        RAISE_APPLICATION_ERROR(-20003,
            'Only customers with a delivered order from this shop can review it.');
    END IF;

    :NEW.last_modified := LOCALTIMESTAMP;
END;
/

-- What a customer may return, and how much of it.
--
-- Two rules, both of which the API also states as a sentence but neither of which
-- the API is trusted to be the only enforcer of:
--
--   1. Only a delivered order can be returned. This is what makes a return and a
--      cancellation provably disjoint — CANCEL_ORDER requires 'pending' — so the
--      stock restore in fn_cleanup_cancelled_order and the restock here can never
--      both fire for the same unit.
--   2. The units returned across all of a customer's accepted requests for one
--      listing cannot exceed what they bought. Without this, three separate
--      requests of two units each on an order of three would restock six.
--      Rejected requests do not count: a customer whose return was refused is
--      entitled to ask again.
--
-- A compound trigger again. Counting a customer's other requests for the same
-- listing means reading product_returns, which the row being written belongs to,
-- so the reading waits until the statement that wrote it is over. The new row is
-- then already in the table and has to be excluded by hand — which is what
-- `LNNVL(r.return_id = ...)` does, and what PostgreSQL spelled
-- `return_id IS DISTINCT FROM NEW.return_id`.
CREATE OR REPLACE TRIGGER trg_check_return_quantity
FOR INSERT OR UPDATE ON product_returns
COMPOUND TRIGGER
    TYPE return_rows IS TABLE OF product_returns%ROWTYPE INDEX BY PLS_INTEGER;
    pending_rows return_rows;
    n PLS_INTEGER := 0;

    BEFORE EACH ROW IS
    BEGIN
        n := n + 1;
        pending_rows(n).return_id := :NEW.return_id;
        pending_rows(n).order_id  := :NEW.order_id;
        pending_rows(n).prod_id   := :NEW.prod_id;
        pending_rows(n).quantity  := :NEW.quantity;
        pending_rows(n).status    := :NEW.status;
    END BEFORE EACH ROW;

    AFTER STATEMENT IS
        v_ordered NUMBER;
        v_state   VARCHAR2(20 CHAR);
        v_already NUMBER;
    BEGIN
        FOR i IN 1 .. n LOOP
            BEGIN
                SELECT oi.quantity, o.order_status
                INTO v_ordered, v_state
                FROM order_items oi
                JOIN orders o ON o.order_id = oi.order_id
                WHERE oi.order_id = pending_rows(i).order_id
                  AND oi.prod_id = pending_rows(i).prod_id;
            EXCEPTION WHEN NO_DATA_FOUND THEN
                RAISE_APPLICATION_ERROR(-20004, 'That listing is not on that order.');
            END;

            IF v_state <> 'delivered' THEN
                RAISE_APPLICATION_ERROR(-20005, 'Only a delivered order can be returned.');
            END IF;

            SELECT COALESCE(SUM(r.quantity), 0) INTO v_already
            FROM product_returns r
            WHERE r.order_id = pending_rows(i).order_id
              AND r.prod_id = pending_rows(i).prod_id
              AND r.status <> 'rejected'
              AND LNNVL(r.return_id = pending_rows(i).return_id);

            -- A rejected request claims nothing, so the new row only counts against
            -- the order line when it is not itself a rejection. Without this test a
            -- refusal recorded while another request was open would be refused in
            -- turn, on the strength of units it never asked for.
            IF pending_rows(i).status <> 'rejected'
               AND v_already + pending_rows(i).quantity > v_ordered THEN
                RAISE_APPLICATION_ERROR(-20006,
                    'A customer cannot return more units than they bought of that listing.');
            END IF;
        END LOOP;
    END AFTER STATEMENT;
END;
/

-- Restrict order lifecycle transitions.
CREATE OR REPLACE TRIGGER trg_guard_order_transition
BEFORE UPDATE ON orders FOR EACH ROW
BEGIN
    IF (:OLD.order_status <> :NEW.order_status OR (:OLD.order_status IS NULL) <> (:NEW.order_status IS NULL))
       AND NOT (
        (:OLD.order_status = 'pending' AND :NEW.order_status IN ('shipped', 'cancelled')) OR
        (:OLD.order_status = 'shipped' AND :NEW.order_status IN ('pending', 'delivered'))
    ) THEN
        RAISE_APPLICATION_ERROR(-20007, 'That order status transition is not allowed.');
    END IF;
END;
/

-- What PostgreSQL enforced with a deferred constraint trigger, and Oracle has no
-- equivalent of: a master product may only be 'available' once every attribute
-- its category requires has a value.
--
-- The two halves cannot be checked in one statement, which is why PostgreSQL
-- deferred the check to the commit — the API writes the master, then its values,
-- and an immediate check would refuse the first write of a perfectly good pair.
-- Oracle deferrs constraints, not triggers, and this is not a constraint.
--
-- So the check lives where the commit does: adminCatalogController runs
-- q.INCOMPLETE_MASTER, the same predicate, as the last statement of saveMaster
-- and saveCategory. A direct SQL writer can still record an incomplete master;
-- nothing in the API can.
CREATE OR REPLACE VIEW incomplete_masters AS
SELECT mp.master_prod_id, mp.name, a.name AS attribute_name
FROM master_products mp
JOIN category_attributes ca ON ca.category_id = mp.category_id
JOIN attributes a ON a.attribute_id = ca.attribute_id
LEFT JOIN attribute_values av
    ON av.master_prod_id = mp.master_prod_id AND av.attribute_id = ca.attribute_id
WHERE mp.active_status = 'available'
  AND (av.attrib_value IS NULL OR TRIM(av.attrib_value) IS NULL);
/

CREATE INDEX idx_orders_user_status ON orders(user_id, order_status)
/
-- Both halves of a courier's view of orders: the run, which is `delivery_person_id
-- = me`, and the open board, which is `delivery_person_id IS NULL AND order_status
-- = 'pending'`. One index on the pair serves both.
CREATE INDEX idx_orders_courier_status ON orders(delivery_person_id, order_status)
/
CREATE INDEX idx_order_items_product ON order_items(prod_id)
/
CREATE INDEX idx_products_shop_master ON products(shop_id, master_prod_id)
/
CREATE INDEX idx_vendor_refunds_shop ON vendor_refunds(shop_id, created_at DESC)
/
CREATE INDEX idx_vendor_refunds_created ON vendor_refunds(created_at DESC)
/
CREATE INDEX idx_shop_topups_shop ON shop_topups(shop_id, created_at DESC)
/
CREATE INDEX idx_product_returns_order ON product_returns(order_id, prod_id)
/
CREATE INDEX idx_product_returns_shop ON product_returns(shop_id, created_at DESC)
/
CREATE INDEX idx_product_returns_courier ON product_returns(status, collected_at)
/
-- One open request per order line. A rejected one is not open, which is what lets
-- a customer whose return was refused ask again; the quantity trigger above is
-- what stops the requests that ARE open from adding up to more than they bought.
--
-- Oracle has no partial index, so the predicate moves into the key: a CASE that
-- yields the order line for an open request and NULL for a closed one. Oracle
-- does not index a key that is entirely NULL, so closed requests drop out of the
-- index rather than colliding in it — the same rule, spelled the way this
-- database can spell it.
CREATE UNIQUE INDEX idx_product_returns_open ON product_returns(
    CASE WHEN status IN ('requested', 'approved', 'collected') THEN order_id END,
    CASE WHEN status IN ('requested', 'approved', 'collected') THEN prod_id END
)
/

-- A real multi-table workflow, called by the delivery API inside a transaction.
-- The guarded transition makes retries safe; a failure rolls back all three writes.
--
-- The courier is paid the order's own delivery_cost rather than a fee computed
-- here. That is the same number the customer was charged, and reading it back
-- from the row means the pay constants in orderQueries.js govern new orders only.
--
-- A procedure, where PostgreSQL wrote a procedure with an INOUT JSONB. Oracle's
-- caller cannot see a return value from a procedure, so the JSON this builds is
-- an OUT bind — which is why the API calls this from an anonymous block rather
-- than as a statement in its own right.
--
-- Every money figure is TO_CHARed to two places before it goes into the JSON.
-- PostgreSQL said `total_amount::text` and got "25.00" from a numeric(12,2);
-- Oracle's implicit conversion would say "25".
CREATE OR REPLACE PROCEDURE settle_delivery(
    p_order_id   IN  NUMBER,
    p_courier_id IN  NUMBER,
    p_result     OUT CLOB
) IS
    v_order_id      orders.order_id%TYPE;
    v_order_status  orders.order_status%TYPE;
    v_delivered_at  orders.delivered_at%TYPE;
    v_total_amount  orders.total_amount%TYPE;
    v_delivery_cost orders.delivery_cost%TYPE;
    v_courier_id    orders.delivery_person_id%TYPE;
    v_payment       CLOB;
    v_courier       CLOB;
BEGIN
    p_result := NULL;

    BEGIN
        UPDATE orders
        SET order_status = 'delivered', delivered_at = LOCALTIMESTAMP
        WHERE order_id = p_order_id AND delivery_person_id = p_courier_id
          AND order_status = 'shipped'
        RETURNING order_id, order_status, delivered_at, total_amount,
                  delivery_cost, delivery_person_id
        INTO v_order_id, v_order_status, v_delivered_at, v_total_amount,
             v_delivery_cost, v_courier_id;
        IF SQL%ROWCOUNT = 0 THEN RETURN; END IF;
    END;

    UPDATE payments SET payment_status = 'completed', paid_at = v_delivered_at
    WHERE order_id = p_order_id AND payment_status = 'pending';

    SELECT JSON_OBJECT(
        'transaction_id' VALUE transaction_id,
        'payment_status' VALUE payment_status,
        'paid_at'        VALUE TO_CHAR(paid_at, 'YYYY-MM-DD"T"HH24:MI:SS')
        RETURNING CLOB)
    INTO v_payment
    FROM payments WHERE order_id = p_order_id;

    UPDATE delivery_personnel
    SET earnings = COALESCE(earnings, 0) + ROUND(v_delivery_cost, 2)
    WHERE delivery_person_id = p_courier_id;

    SELECT JSON_OBJECT(
        'delivery_person_id' VALUE delivery_person_id,
        'earnings'           VALUE TO_CHAR(earnings, 'FM9999999990.00')
        RETURNING CLOB)
    INTO v_courier
    FROM delivery_personnel WHERE delivery_person_id = p_courier_id;

    -- Pay each shop for its own lines, in full. There is no commission between
    -- the customer's payment and the shop, and the delivery charge on this order
    -- is the courier's, not the shop's. One statement for however many shops the
    -- order spans: PostgreSQL grouped a joined subquery, which Oracle expresses
    -- as a correlated one.
    --
    -- A sale credits the balance when it is delivered, not when it is placed: an
    -- order still in a van is not money the shop can spend on stock.
    --
    -- The shop is named by its table for the same reason as above: SET takes a
    -- bare column name, so there is no alias for the correlated subquery to use.
    UPDATE shops
    SET balance = balance + (
        SELECT COALESCE(SUM(oi.quantity * oi.unit_price), 0)
        FROM order_items oi
        JOIN products p ON p.prod_id = oi.prod_id
        WHERE oi.order_id = p_order_id AND p.shop_id = shops.shop_id)
    WHERE EXISTS (
        SELECT 1 FROM order_items oi
        JOIN products p ON p.prod_id = oi.prod_id
        WHERE oi.order_id = p_order_id AND p.shop_id = shops.shop_id);

    SELECT JSON_OBJECT(
        'order_id'           VALUE v_order_id,
        'order_status'       VALUE v_order_status,
        'delivered_at'       VALUE TO_CHAR(v_delivered_at, 'YYYY-MM-DD"T"HH24:MI:SS'),
        'total_amount'       VALUE TO_CHAR(v_total_amount, 'FM9999999990.00'),
        'delivery_cost'      VALUE TO_CHAR(v_delivery_cost, 'FM9999999990.00'),
        'delivery_person_id' VALUE v_courier_id,
        'payment'            VALUE v_payment FORMAT JSON,
        'courier_earnings'   VALUE v_courier FORMAT JSON
        RETURNING CLOB) INTO p_result FROM dual;
END;
/
