const BEGIN_TRANSACTION = "BEGIN";
const COMMIT_TRANSACTION = "COMMIT";
const ROLLBACK_TRANSACTION = "ROLLBACK";

module.exports = {
  BEGIN_TRANSACTION,
  COMMIT_TRANSACTION,
  ROLLBACK_TRANSACTION,
};
